server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.game.po
  configuration:
    map-underscore-to-camel-case: true
  #开启驼峰命名转换
#分页插件
#pagehelper.helper-dialect=mysql
#pagehelper.params=count=countSql
#pagehelper.reasonable=true
#pagehelper.support-methods-arguments=true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
spring:
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://127.0.0.1:3306/game?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave:
        enabled: true
        url: jdbc:mysql://127.0.0.1:3306/sell?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456


  jms:
    pub-sub-domain: true
  redis:
    host: localhost
    port: 6379
    redis:
        host: localhost
        port: 6379
        jedis:
          pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
        timeout: 0
  rabbitmq:
    host: 192.168.72.128
    port: 5673
    username: guest
    password: guest

#打印sql语句
logging:
  level:
    com.example.game.dao: debug