server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.game.po
#分页插件
#pagehelper.helper-dialect=mysql
#pagehelper.params=count=countSql
#pagehelper.reasonable=true
#pagehelper.support-methods-arguments=true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
spring:
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/game?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jms:
    pub-sub-domain: true
  redis:
    host: localhost
    port: 6379
    redis:
        host: localhost
        port: 6379
        jedis:
          pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
        timeout: 0
#打印sql语句
logging:
  level:
    com.example.game.dao: debug